### ISSUE TITLE
Set output format after driver initialization

### ISSUE THREAD

**Issue by adomasven** [zotero/citeproc-rs#122]
Could we have a `setOutputFormat()` API if it doesn't require reinitializing something fundamental in the driver? We can adjust Zotero code to only ever set output format on driver initialization but we might have plugins that are used to calling `setOutputFormat()` available on citeproc-js and we don't want to break them unnecessarily.

**Comment by cormacrelf** [comment]
These plugins own their own instance, right? If so, the format change doesn't need to be temporary, it can happily invalidate large swaths of the cache. I believe this is [what citeproc-js does.](https://github.com/Juris-M/citeproc-js/blob/aa2683f48fe23be459f4ed3be3960e2bb56203f0/src/api_control.js#L8). So yeah, I can do that for you.

As I am sure I have detailed before/elsewhere, the invalidation requirement is a disambiguation thing -- if the output format is plain, and you have a style that uses italics to differentiate between e.g. books and journal articles, then you want to ignore the italics for disambiguating  'Jones, Title, 1999' and 'Jones, *Title*, 1999'. In plain mode it should go further and make them 1999a/b or whatever step comes next. In order to change what happens here you have to invalidate large parts of the computation graph. Because I knew this was going to be the case, I didn't even put the format in the dependency graph, but it will be pretty easy to change the implementation of the "get format" function.

(Either that or just manually wipe, which I think would also be pretty easy since it's all in the one section of the db. In the terminology of the graph citeproc-rs uses (Salsa), if it's in the graph, the output format should be set with "high durability" so the engine can avoid checking a node whose dependencies are more durable than the highest-durability change since last check. This is nice, because the format presumably does not change often, but nearly every node in the graph depends on it.)

You would have noticed that the `previewCitationCluster` API already has a custom output format option. This can be "incorrect" in the way I described, which you can observe by asking for plain output when the internal format is HTML, or vice versa. This doesn't actually warrant consternation, because it's a faithful preview of what would actually appear in the document, just in another format. So it's actually more correct than rebuilding the whole thing from scratch for every single preview call.

**Comment by adomasven** [comment]
I'm not creating bridge functions for `processCitationCluster()` of citeprocJS, so that might still introduce incompatibilities with our plugin developers. If this too much of an undertaking you shouldn't prioritize it too highly.

**Comment by cormacrelf** [comment]
Oh, also semi-related, the free() API would be required of any plugin authors still. FF ESR 78 doesn't have "weak refs" aka auto free so Zorero-bundled citeproc-rs can't use it until ESR 91. Calling free when weak refs are enabled doesn't break anything so that can be added later and the free() call can be made optional.

I am not familiar with the plugin API, but if it has lifecycle events like "unloading plugin" then that would be where to put free() calls.
