### ISSUE TITLE
"<" is ignored in prefix

### ISSUE THREAD

**Issue by tnajdek** [zotero/citeproc-rs#129]
Some styles use "<" character in prefix (encoded as `&lt;`). This seems to be ignored and doesn't render.

**Comment by cormacrelf** [comment]
Prefixes of what kinds of things? I can't reproduce this on a `<text variable="title">` or URL, but there could be another element that has this problem. (It occurs to me I should make it so the demo/playground can give you shareable links.)

![image](https://user-images.githubusercontent.com/378760/139526006-2f546b13-8d45-4a99-b1f0-cc31bce23a5a.jpeg)

**Comment by tnajdek** [comment]
Sorry, it was quite late here when I've seen this and I just wanted to note down the issue so I don't forget.

I've seen this behaviour for DOI, it seems to happen regardless of `link_anchors` value. Here is an example CSL (from [MHRA](https://www.zotero.org/styles/modern-humanities-research-association)):
````xml
<text variable="DOI" prefix=" &lt;https://doi.org/" suffix="&gt;"/>
````

And here is screenshot from the playground:

<img width="237" alt="Screenshot 2021-10-30 at 11 06 16" src="https://user-images.githubusercontent.com/214628/139527037-ae9bc898-8346-465a-babd-ce632e7ef981.png">

**Comment by cormacrelf** [comment]
Oh, I see it. It is over-parsing the affixes, because the superscript parser is only used inside the HTML parser. It needs to parse the hacky superscripts, but not actual HTML. The HTML5 parser used in citeproc-rs dutifully (and I presume correctly according to that spec) ignored an incomplete/invalid `<https:` tag and swallowed the rest of the input.

The affixes have their XML entities pre-processed, so that part is already done, the HTML parser doesn't need to be involved at all.

**Comment by cormacrelf** [comment]
This is a good catch, thanks.
