### ISSUE TITLE
Plaintext output of citations does not handle unicode characters properly

### ISSUE THREAD

**Issue by adomasven** [zotero/citeproc-rs#91]
Plaintext output of citations (at least with the `previewCitationCluster()`) produces output like:

> \uc0\u268 otar et al., 2020

where it should be

> Čotar et al., 2020

The bibliography plaintext output for unicode characters is fine.

**Comment by cormacrelf** [comment]
Ah, that's a dumb but easy one. Good catch.

```
let build = built_cluster_before_output(db, cluster_id);
let string = formatter.output(build, get_piq(db));
Arc::new(string)
```

What's missing here? Using the overridden formatter inside built_cluster_before_output, Cormac you idiot. Hence the Unicode encoded for RTF.

**Comment by cormacrelf** [comment]
Turns out this code was fine. You need to pass one of `"html"`, `"rtf"` or `"plain"`, and it was not raising an error when it wasn't one of these, it just silently used the driver's default output format. I've got a PR to make it raise errors & document slightly more, but you'll have to check that you're not writing `"plaintext"` instead of `"plain"`.
